# E-commerce Product Recommendation using RBM

Dataset: Online Retail dataset (UCI / Kaggle)

Goal: Build a Restricted Boltzmann Machine (RBM) based recommender system that suggests products based on customer purchase history.

## 1. Import Libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.neural_network import BernoulliRBM

## 2. Load Dataset

In [ ]:
df = pd.read_csv('OnlineRetail.csv', encoding='ISO-8859-1')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

## 3. Data Cleaning

In [ ]:
df = df.dropna(subset=['CustomerID'])
df = df[df['Quantity'] > 0]
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

## 4. Reduce Dataset Size (for Colab stability)

In [ ]:
top_customers = df['CustomerID'].value_counts().head(500).index
df = df[df['CustomerID'].isin(top_customers)]

## 5. Create User–Item Matrix

In [ ]:
user_item = df.pivot_table(
    index='CustomerID',
    columns='Description',
    values='Quantity',
    aggfunc='sum'
)

user_item = user_item.fillna(0)
user_item.head()

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC PLANT POT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
CustomerID,,,,,,,,,,,,,,,,,,,,,
12359.0,0.0,0.0,12.0,4.0,0.0,4.0,0.0,0.0,6.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12362.0,0.0,0.0,12.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12378.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12415.0,0.0,0.0,200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12417.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 6. Convert Purchases to Binary

In [ ]:
matrix = user_item.copy()
matrix[matrix > 0] = 1
matrix.head()

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC PLANT POT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
CustomerID,,,,,,,,,,,,,,,,,,,,,
12359.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12362.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12378.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12415.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12417.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 7. Train RBM

In [ ]:
rbm = BernoulliRBM(n_components=50, learning_rate=0.01, n_iter=15, verbose=True)
rbm.fit(matrix)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(

[BernoulliRBM] Iteration 1, pseudo-likelihood = -1942.94, time = 0.71s

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(

[BernoulliRBM] Iteration 2, pseudo-likelihood = -1871.05, time = 0.43s

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(

[BernoulliRBM] Iteration 3, pseudo-likelihood = -2062.53, time = 0.26s
[BernoulliRBM] Iteration 4, pseudo-likelihood = -1824.28, time = 0.18s

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(

[BernoulliRBM] Iteration 5, pseudo-likelihood = -1359.29, time = 0.19s
[BernoulliRBM] Iteration 6, pseudo-likelihood = -1453.02, time = 0.20s

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(

[BernoulliRBM] Iteration 7, pseudo-likelihood = -2308.90, time = 0.19s
[BernoulliRBM] Iteration 8, pseudo-likelihood = -1237.16, time = 0.21s

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(

[BernoulliRBM] Iteration 9, pseudo-likelihood = -1302.48, time = 0.18s
[BernoulliRBM] Iteration 10, pseudo-likelihood = -921.85, time = 0.19s

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(

[BernoulliRBM] Iteration 11, pseudo-likelihood = -1799.00, time = 0.21s
[BernoulliRBM] Iteration 12, pseudo-likelihood = -969.31, time = 0.17s

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(

[BernoulliRBM] Iteration 13, pseudo-likelihood = -1112.22, time = 0.18s
[BernoulliRBM] Iteration 14, pseudo-likelihood = -1286.06, time = 0.17s
[BernoulliRBM] Iteration 15, pseudo-likelihood = -915.01, time = 0.18s

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(

BernoulliRBM(learning_rate=0.01, n_components=50, n_iter=15, verbose=True)

## 8. Generate Recommendations

In [ ]:
user_index = 0
user_vector = matrix.iloc[user_index].values.reshape(1,-1)

hidden = rbm.transform(user_vector)
reconstructed = np.dot(hidden, rbm.components_)

scores = reconstructed.flatten()
products = matrix.columns

recommendations = pd.DataFrame({
    'Product': products,
    'Score': scores
}).sort_values(by='Score', ascending=False)

recommendations.head(10)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliRBM was fitted with feature names
  warnings.warn(

                                 Product      Score
1825             LUNCH BAG RED RETROSPOT  45.622272
3507  WHITE HANGING HEART T-LIGHT HOLDER  44.755853
2134     PACK OF 72 RETROSPOT CAKE CASES  40.411426
2608            REGENCY CAKESTAND 3 TIER  39.648851
1656             JUMBO BAG RED RETROSPOT  37.311863
2206                       PARTY BUNTING  28.287355
1817             LUNCH BAG  BLACK SKULL.  25.967741
1828          LUNCH BAG SPACEBOY DESIGN   24.427957
2832   SET OF 3 CAKE TINS PANTRY DESIGN   21.778525
3145                      SPOTTY BUNTING  20.973502